import Link from "next/link";
import { notFound } from "next/navigation";
import { AdminHeader } from "@/components/admin-header";
import { ArchiveItemForm, MenuItemForm, MenuOptionForm, OptionGroupForm } from "@/features/menu-management/admin-forms";
import { requirePermission } from "@/server/auth/authorization";
import { getAdminCategories, getAdminMenuItem } from "@/server/menu/admin-catalog";

export default async function EditItemPage({ params }: { params: Promise<{ id: string }> }) { const user = await requirePermission("menu:write"); const { id } = await params; const [item, categories] = await Promise.all([getAdminMenuItem(id), getAdminCategories()]); if (!item) notFound(); return <main className="admin-container max-w-5xl"><AdminHeader user={user} /><section className="py-8" id="workspace-content" tabIndex={-1}><Link className="text-sm font-semibold text-copper hover:underline" href="/admin/menu">← Menu management</Link><p className="eyebrow mt-5">Catalog item</p><h1 className="mt-2 text-4xl font-semibold tracking-[-0.04em]">Edit {item.name}</h1><div className="mt-7 space-y-7"><MenuItemForm categories={categories} item={item} /><section className="surface-card p-5 sm:p-7"><h2 className="text-2xl font-semibold">Option groups</h2><p className="mt-2 text-sm leading-6 text-muted">Inactive groups and unavailable choices stay out of the public configurator.</p><div className="mt-5 space-y-6">{item.optionGroups.map((group) => <section className="space-y-3 rounded-2xl border border-line bg-background/30 p-3 sm:p-4" key={group.id}><OptionGroupForm group={group} menuItemId={item.id} /><div className="space-y-2 sm:pl-4">{group.options.map((option) => <MenuOptionForm key={option.id} menuItemId={item.id} option={option} optionGroupId={group.id} />)}<MenuOptionForm menuItemId={item.id} optionGroupId={group.id} /></div></section>)}<div><h3 className="mb-2 font-semibold">Add an inactive group</h3><OptionGroupForm menuItemId={item.id} /></div></div></section><ArchiveItemForm archived={item.isArchived} id={item.id} /></div></section></main>; }

